# Generated by Django 6.0.3 on 2026-04-07 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('N1', 'Liviano N1 (2.5-3.5 t)'), ('N2', 'Mediano N2 (4.5-5.5 t)')], max_length=2)),
                ('capacidad_ton', models.DecimalField(decimal_places=2, max_digits=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TarifaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_por_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_ayudante', models.DecimalField(decimal_places=2, help_text='Precio por ayudante por mudanza', max_digits=8)),
                ('recargo_piso', models.DecimalField(decimal_places=2, help_text='Recargo por piso sin ascensor', max_digits=8)),
                ('activa', models.BooleanField(default=True)),
                ('vigente_desde', models.DateField()),
            ],
            options={
                'verbose_name': 'Tarifa base',
                'verbose_name_plural': 'Tarifas base',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('AYUDANTE', 'Ayudante de carga'), ('ADMIN', 'Administrativo')], max_length=20)),
                ('nro_licencia', models.CharField(blank=True, max_length=50, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Mudanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PRESUPUESTADA', 'Presupuestada'), ('CONFIRMADA', 'Confirmada (seña pagada)'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('POSPUESTA', 'Pospuesta')], default='BORRADOR', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('domicilio_origen', models.CharField(max_length=300)),
                ('domicilio_destino', models.CharField(max_length=300)),
                ('lat_origen', models.FloatField(blank=True, null=True)),
                ('lng_origen', models.FloatField(blank=True, null=True)),
                ('lat_destino', models.FloatField(blank=True, null=True)),
                ('lng_destino', models.FloatField(blank=True, null=True)),
                ('piso_origen', models.PositiveSmallIntegerField(default=0)),
                ('ascensor_origen', models.BooleanField(default=False)),
                ('piso_destino', models.PositiveSmallIntegerField(default=0)),
                ('ascensor_destino', models.BooleanField(default=False)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('necesita_ayudantes', models.BooleanField(default=True)),
                ('monto_senia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('senia_pagada', models.BooleanField(default=False)),
                ('mp_preference_id', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudanzas', to='gestion.camion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mudanzas', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Mudanza',
                'verbose_name_plural': 'Mudanzas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HELADERA', 'Heladera'), ('LAVARROPAS', 'Lavarropas'), ('CAMA', 'Cama'), ('SOFA', 'Sofá'), ('MESA', 'Mesa comedor'), ('PLACARD', 'Placard / Ropero'), ('CAJA', 'Caja / Bulto'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('mudanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion.mudanza')),
            ],
            options={
                'verbose_name': 'Ítem de inventario',
                'verbose_name_plural': 'Ítems de inventario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFIRMACION', 'Confirmación de mudanza'), ('RECORDATORIO', 'Recordatorio 24hs'), ('CANCELACION', 'Cancelación'), ('POSPOSICION', 'Posposición'), ('LINK_PAGO', 'Link de pago seña')], max_length=20)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20)),
                ('destinatario', models.CharField(max_length=200)),
                ('enviada', models.BooleanField(default=False)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('mudanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.mudanza')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-enviada_en'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_peajes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_ayudantes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_camion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo_pisos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('mudanza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='gestion.mudanza')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.tarifabase')),
            ],
            options={
                'verbose_name': 'Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('AYUDANTE', 'Ayudante de carga'), ('ADMIN', 'Administrativo')], max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='gestion.empleado')),
                ('mudanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion.mudanza')),
            ],
            options={
                'verbose_name': 'Asignación de empleado',
                'verbose_name_plural': 'Asignaciones de empleados',
                'unique_together': {('mudanza', 'empleado')},
            },
        ),
    ]
