# Generated by Django 6.0.3 on 2026-04-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='capacidad_ton',
        ),
    ]
