# Generated by Django 6.0.3 on 2026-04-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_camion_capacidad_ton'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
