# Generated by Django 6.0.3 on 2026-04-17 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('volumen_m3', models.DecimalField(decimal_places=3, max_digits=6)),
                ('peso_estimado_kg', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Ítem de catálogo',
                'verbose_name_plural': 'Ítems de catálogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.PositiveSmallIntegerField(default=0)),
                ('departamento', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('tiene_ascensor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='mudanza',
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='ascensor_destino',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='ascensor_origen',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='domicilio_destino',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='domicilio_origen',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='lat_destino',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='lat_origen',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='lng_destino',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='lng_origen',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='piso_destino',
        ),
        migrations.RemoveField(
            model_name='mudanza',
            name='piso_origen',
        ),
        migrations.AddField(
            model_name='camion',
            name='anio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camion',
            name='capacidad_peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso máximo', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camion',
            name='capacidad_volumen_m3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volumen máximo', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camion',
            name='ultima_revision_tecnica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='catalogo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='gestion.catalogoitem'),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='destino',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='mudanzas_como_destino', to='gestion.direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mudanza',
            name='origen',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='mudanzas_como_origen', to='gestion.direccion'),
            preserve_default=False,
        ),
    ]
