# Generated by Django 6.0.3 on 2026-04-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_migrate_domicilios_to_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='mudanza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion.mudanza'),
        ),
    ]
