# Generated by Django 6.0.3 on 2026-04-17 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_fix_iteminventario_restaurar_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='mudanza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion.mudanza'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FotoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('CARGA', 'Carga'), ('DESCARGA', 'Descarga')], max_length=10)),
                ('imagen', models.ImageField(upload_to='inventario/%Y/%m/')),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('mudanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestion.mudanza')),
            ],
            options={
                'verbose_name': 'Foto de inventario',
                'verbose_name_plural': 'Fotos de inventario',
                'ordering': ['momento', 'subida_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PRESUPUESTADA', 'Presupuestada'), ('CONFIRMADA', 'Confirmada (seña pagada)'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('POSPUESTA', 'Pospuesta')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PRESUPUESTADA', 'Presupuestada'), ('CONFIRMADA', 'Confirmada (seña pagada)'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('POSPUESTA', 'Pospuesta')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mudanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestion.mudanza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha'],
            },
        ),
    ]
