# Generated by Django 6.0.3 on 2026-04-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_fase2_fotos_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='ultima_revision_tecnica',
            new_name='patente_fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='camion',
            name='seguro_fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='vtv_fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='ascensor_grande',
            field=models.BooleanField(default=False, help_text='¿Entra un colchón/sofá?'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='capacidad_ascensor_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='art',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='licencia_fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='seguro_ayudante_carga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='seguro_riesgo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='empleado_art',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='empleado_seguro_ayudante',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='empleado_seguro_riesgo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='permite_caba_feriados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='recargo_fin_de_semana',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=5),
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='recargo_hora_pico',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Multiplicador (ej: 1.20 para +20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='salario_ayudante',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='salario_conductor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifabase',
            name='seguro_camion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.CharField(default='PB', max_length=10),
        ),
    ]
