# Generated by Django 6.0.3 on 2026-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_rename_ultima_revision_tecnica_camion_patente_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='en_taller',
            field=models.BooleanField(default=False, help_text='Marca el vehículo como fuera de servicio por mantenimiento o reparación.'),
        ),
    ]
