# Generated by Django 6.0.3 on 2026-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_camion_en_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoitem',
            name='categoria',
            field=models.CharField(choices=[('LIVING', 'Living'), ('DORMITORIO', 'Dormitorio'), ('COCINA', 'Cocina'), ('OFICINA', 'Oficina'), ('VARIOS', 'Varios')], db_index=True, default='VARIOS', max_length=20),
        ),
        migrations.DeleteModel(
            name='FotoInventario',
        ),
    ]
