# Generated by Django 6.0.3 on 2026-06-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_catalogoitem_categoria_delete_fotoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
