# Generated by Django 6.0.3 on 2026-06-10 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_catalogoitem_categoria_delete_fotoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='SesionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_id', models.CharField(db_index=True, help_text='Telefono (WA) o sesion_key (web).', max_length=100)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WEB', 'Pop-up Web')], max_length=20)),
                ('flujo_detectado', models.CharField(choices=[('LANDING', 'Entrada desde Landing Page'), ('GENERAL', 'Entrada General'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20)),
                ('atencion_manual', models.BooleanField(default=False, help_text='True cuando el usuario solicito hablar con un operador.')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesion de chatbot',
                'verbose_name_plural': 'Sesiones de chatbot',
                'ordering': ['-actualizada_en'],
                'unique_together': {('canal_id', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='MensajeChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('USUARIO', 'Usuario'), ('BOT', 'Bot')], max_length=10)),
                ('texto', models.TextField()),
                ('enviado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='gestion.sesionchatbot')),
            ],
            options={
                'verbose_name': 'Mensaje de chatbot',
                'verbose_name_plural': 'Mensajes de chatbot',
                'ordering': ['enviado_en'],
            },
        ),
    ]
