# Generated by Django 6.0.3 on 2026-06-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_cliente_telefono_sesionchatbot_mensajechatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='notificacion_24h_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='notificacion_seguimiento_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
