# Generated by Django 6.0.3 on 2026-06-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_cliente_telefono'),
        ('gestion', '0017_mudanza_notificacion_24h_enviada_and_more'),
    ]

    operations = [
    ]
