# Generated by Django 6.0.3 on 2026-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_merge_20260619_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
